name: Release
on:
  workflow_dispatch:
  pull_request:
  
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.1.beta20220831-1
    steps:
      - name: Setup - checkout
        uses: actions/checkout@v3

      - name: docker
        shell: bash    
        run: |
          docker/build.sh -v 
