name: Release
on:
  workflow_dispatch:
  pull_request:
  
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: 1.0.1.beta20220831-12
    steps:
      - name: Setup - checkout
        uses: actions/checkout@v3
        
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi
          
      - name: Build
        run: go build -v cmd/arcade/arcade.go

      - name: Test
        run: go test -v ./...

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker
        shell: bash    
        run: |
          ls -l arcade
          file arcade
          rm arcade
          docker/build.sh -v ${VERSION}
          ls -l arcade
          file arcade
